CSU-Booking-Platform/application

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/spike.md
- .github/ISSUE_TEMPLATE/user-story.md
- .github/PULL_REQUEST_TEMPLATE.md
n/a documentation only
- Closes #3 
- Closes #2
> fix: Create issue templates 

- .circleci/config.yml
- .github/dependabot.yaml
- .gitignore
- phpunit.xml
- sonar-project.properties
Configuring Sonarcloud static analysis, dependabot & Slack CircleCI Alerts
n/a tool configuration
- closes #7, #52, #8 
> Configuring static analysis, Dependabot & Slack CI Alerts

- .circleci/config.yml
Add versioning to the project
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots/videos if the pull request changes UI.
- closes #75 
> chore(#75): Add tag-and-release ci job

- .circleci/config.yml
FIxing broken versioning job by adding shared workspace
> chore(#75): Fix attempt for release & tag

- README.md
Updating the readme with relevant content: dependencies, installation steps, links to docs and resources, etc.
This is a text file
- closes #51
> task(#51): update readme

- .github/PULL_REQUEST_TEMPLATE.md
> doc: add sub-task to PR TEMPLATE

- .circleci/config.yml
- .devcontainer/docker-compose.yml
- .devcontainer/setup.sh
- mkver.conf
Fixes broken versioning
- Closes #86 
n/a CI fixes
> fix(#86): Fix release process

- composer.json
- composer.lock
- tests/Browser/ExampleTest.php
- tests/Browser/Pages/HomePage.php
- tests/Browser/Pages/Page.php
- tests/Browser/console/.gitignore
- tests/Browser/screenshots/.gitignore
- tests/DuskTestCase.php
Install laravel dusk for browser testing.
> 42 installing dusk

- .circleci/config.yml
- .gitignore
- package-lock.json
- package.json
- phpunit.xml
- sonar-project.properties
- tests/Javascript/Dashboard.spec.js
Installing Jest & related components for JS testing
> chore(#34): Install and configure JEST

- app/Http/Controllers/UserController.php
- package-lock.json
- resources/js/Pages/Admin/Users/Index.vue
- resources/js/Pages/Admin/Users/UsersList.vue
- routes/web.php
- tests/Feature/UserControllerTest.php
- tests/Javascript/Pages/Admin/Users/UsersList.spec.js
Admins can assign roles to users & edit users.
Testing is passing
- Closes #38 
> #38: Assign roles to users & edit users

- app/Http/Controllers/RoomController.php
- app/Models/Room.php
- database/factories/RoomFactory.php
- database/migrations/2020_11_21_160732_create_rooms_table.php
- resources/js/Pages/Admin/Rooms/CreateRoomForm.vue
- resources/js/Pages/Admin/Rooms/Index.vue
- routes/web.php
- tests/Feature/RoomControllerTest.php
- tests/Javascript/Pages/Admin/Rooms/CreateRoom.spec.js
- tests/Javascript/Pages/Admin/Rooms/Index.spec.js
> feat(#39): Create a room

- resources/js/Pages/Admin/Rooms/Index.vue
- resources/js/Pages/Admin/Rooms/RoomsList.vue
- tests/Javascript/Pages/Admin/Rooms/RoomsList.spec.js
- Shows the rooms on a page.
`<insert>`
- `closes #37 ` 
> feat(#37): View all Rooms

- app/Http/Controllers/RoomController.php
- resources/js/Pages/Admin/Rooms/RoomsList.vue
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
- routes/web.php
- tests/Feature/RoomControllerTest.php
- tests/Javascript/Pages/Admin/Rooms/UpdateRoomForm.spec.js
- tests/Javascript/__mocks__/laravel-jetstream.js
Update a room
User story
Checks pass
- `closes #55 ` 
> feat(#55): update a room

- public/.gitignore
- public/css/global.css
- resources/views/app.blade.php
- resources/views/layouts/guest.blade.php
Global CSS file that specifies color and font theme for each component in the current app prototypes. 
Confirmation that the CSS properties reflect the UI prototype theme.
- `closes #211` 
> Task(#211): Theme Creation

- resources/js/Layouts/AppLayout.vue
Simple static footer component
Closes #213 
> feat(#213): Add footer component

- .github/ISSUE_TEMPLATE/task.md
Update task template
- `closes #XXXX` 
> Update task template

- app/Http/Controllers/BookingRequestController.php
- app/Models/BookingRequest.php
- database/migrations/2020_12_30_162406_add_reference.php
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestForm.vue
- resources/js/Pages/Admin/BookingRequests/UpdateBookingRequestForm.vue
- tests/Feature/BookingRequestControllerTest.php
- tests/Javascript/Pages/Admin/BookingRequests/BookingRequestsList.spec.js
- tests/Javascript/Pages/Admin/BookingRequests/CreateBookingRequest.spec.js
- tests/Javascript/Pages/Admin/BookingRequests/UpdateBookingRequestForm.spec.js
Allows users to upload files with their booking request submission. Files can be added at booking creation or later by updating an existing booking.
Tests have passed.
- closes #29  
> feat(#29): attach reference files to bookings

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/RoomController.php
- app/Models/Availability.php
- app/Models/Room.php
- database/migrations/2020_12_29_142917_create_availabilities_table.php
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestForm.vue
- resources/js/Pages/Admin/BookingRequests/UpdateBookingRequestForm.vue
- resources/js/Pages/Admin/Rooms/CreateRoomForm.vue
- tests/Feature/BookingRequestControllerTest.php
- tests/Feature/RoomControllerTest.php
#22 
#22
checks have passed
- `closes #22 ` 
> feat(#22): time restrictions for rooms

- app/Http/Controllers/UserController.php
- resources/js/Pages/Admin/Users/UsersList.vue
- tests/Javascript/Pages/Admin/Users/UsersList.spec.js
Resolves bug #209
- Closes #209 
> Bugfix: Fix user update form 

- app/Http/Controllers/UserController.php
- resources/js/Pages/Admin/Users/UsersList.vue
- tests/Javascript/Pages/Admin/Users/UsersList.spec.js
> Replay #270

- README.md
- app/Http/Controllers/BookingRequestController.php
- app/Models/BookingRequest.php
- app/Models/Room.php
- composer.json
- database/factories/RoomFactory.php
- database/migrations/2021_01_10_191410_add_date_restriction_columns_to_rooms.php
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestForm.vue
- resources/js/Pages/Admin/BookingRequests/UpdateBookingRequestForm.vue
- resources/js/Pages/Admin/Rooms/CreateRoomForm.vue
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
- resources/views/app.blade.php
- tests/Feature/BookingRequestControllerTest.php
Allows admins to define how early and how late in advance rooms can be booked. 
This means that rooms can't be booked earlier that "X" days in advance, or later than "Y" days in advance. 
Also, updated the ReadMe with information on testing. 
When rooms have a minimum and maximum days in advance to book, if a booking is made outside of that window it fails and an error message is given to the user explaining the exact booking window of that room. 
- closes #18 …
> feat(#18): Booking Restrictions Per Room

- composer.json
- composer.lock
Rollback of jetstream breaking changes during v1 to v2 update by dependabot.
- Auth pages are back
- Everything else still works and code passes tests
> fix(#307): rollback breaking changes done in jetstream major update

- .circleci/config.yml
Enables commit message validation in CI for PRs
> fix: Validate commit messages in PR

- .circleci/config.yml
- commitlint.config.js
Use different cli for message validation
> fix: Validate commit messages in PR using commitlint

- app/Http/Controllers/SettingsController.php
- database/factories/RoleFactory.php
- tests/Feature/SettingsControllerTest.php
This PR is being made in response to sonar clouds security warning. 
We no longer use the default laravel name hash since it uses input from the user to generate it. 
This code updates php tests for backend functionality. 
- closes #321 
- closes #230 
> 321 upload security

- resources/js/Components/FormSection.vue
Submit buttons on the custom form component now work.
Fixes bug #352 
- closes #352 
> fix(#352): Fix custom form component

- .circleci/config.yml
- .env.ci
- app/Providers/AppServiceProvider.php
- composer.json
- composer.lock
- database/migrations/2020_12_15_204231_create_settings_table.php
- database/migrations/2020_12_30_162406_add_reference.php
- database/migrations/2021_01_14_212158_add_attributes_columns_to_rooms_table.php
- phpunit.xml
- resources/views/auth/login.blade.php
- tests/Browser/ExampleTest.php
- tests/Browser/LoginTest.php
- tests/DuskTestCase.php
Setup for Laravel Dusk Testing
n/a
- Closes #349 
> Automated testing with Dusk

- .circleci/config.yml
- tests/DuskTestCase.php
Bug fix for coverage reporting
> fix: attempt to fix test coverage

- app/Http/Controllers/BlackoutController.php
- app/Models/Blackout.php
- app/Models/Room.php
- database/factories/BlackoutFactory.php
- database/migrations/2021_01_23_212647_create_room_blackouts_table.php
- database/migrations/2021_01_24_200130_add_colum_to_blackouts.php
- resources/js/Components/FormSection.vue
- resources/js/Components/Tables/BlackoutsTable.vue
- resources/js/Pages/Admin/Blackouts/BlackoutList.vue
- resources/js/Pages/Admin/Blackouts/CreateBlackoutForm.vue
- resources/js/Pages/Admin/Blackouts/Room.vue
- resources/js/Pages/Admin/Rooms/RoomsList.vue
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
- routes/web.php
- tests/Feature/BlackoutControllerTest.php
- tests/Javascript/Pages/Admin/Blackout/BlackoutList.spec.js
- tests/Javascript/Pages/Admin/Blackout/CreateBlackout.spec.js
- tests/Javascript/Pages/Admin/Blackout/UpdateBlackoutForm.spec.js
test(#246): Added tests for blackout feature (frontend + backend)
refactor(#246): Compressed Roomlist menu items into dropdown menu
Adds the feature to black out rooms for specific periods (days or hours/minutes). This lets admins define holidays or other periods where rooms are unbookable.
These periods can be updated and deleted as necessary.
- closes #246 
> feat(#246): Add blackout feature

- app/Http/Controllers/BlackoutController.php
- app/Models/AcademicDate.php
- database/migrations/2021_01_26_024607_create_academic_dates.php
- database/seeders/AcademicDatesSeeder.php
- database/seeders/DatabaseSeeder.php
- resources/js/Pages/Admin/Blackouts/CreateBlackoutForm.vue
- tests/Feature/BlackoutControllerTest.php
[https://github.com/CSU-Booking-Platform/application/issues/329](url)
[https://github.com/CSU-Booking-Platform/application/issues/329](url)
- checks
- closes #329
> feat(#329): recurring blackout period

- app/Http/Controllers/RoomController.php
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
- tests/Feature/RoomControllerTest.php
[ #337 ](https://github.com/CSU-Booking-Platform/application/issues/327)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots/videos if the pull request changes UI.
see checks
- `closes #327 ` 
> feat(#327): Update availabilities

- resources/views/layouts/guest.blade.php
Fix security issue in sonar:
Replace cdn link for alpine js with one that has integrity check.
- closes #388
> fix(#388): update cdn link with integrity for alpinejs

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/ReservationsController.php
- app/Http/Controllers/RoleController.php
- app/Models/User.php
- database/factories/RoleFactory.php
- database/migrations/2021_01_23_002513_add_booking_restrictions_to_roles_table.php
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestForm.vue
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- resources/js/Pages/Admin/Roles/CreateRoleForm.vue
- resources/js/Pages/Admin/Roles/UpdateRoleForm.vue
- tests/Feature/BookingRequestControllerTest.php
[https://github.com/CSU-Booking-Platform/application/pull/326#workspaces/csu-booking-platform-5f53df8cc83276001f008d46/board?repos=292935927](url)
[https://github.com/CSU-Booking-Platform/application/pull/326#workspaces/csu-booking-platform-5f53df8cc83276001f008d46/board?repos=292935927](url)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots/videos if the pull request changes UI.
- See checks
- Closes #245
> feat(#245): add booking restrictions on roles

- app/Models/AcademicDate.php
- tests/Feature/BlackoutControllerTest.php
[https://github.com/CSU-Booking-Platform/application/issues/394](url)
[https://github.com/CSU-Booking-Platform/application/issues/394](url)
- closes #394
> fix(#394): resolve flaky daily blackout test

- resources/js/Components/Navbar/Navbar.vue
> fix(#409): routes are generated from root in navbar

- app/Http/Controllers/RoomController.php
- tests/Feature/RoomControllerTest.php
Solve bug #408 where creating a room didn't save the min/max day values. 
Add check in feature test to check and see if max/min day is in the DB. 
- closes #408
> fix 408 bug

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/ReservationsController.php
- app/Http/Controllers/RoomController.php
- package-lock.json
- package.json
- resources/js/Components/AvailabilitiesModal.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Components/Tables/ViewActiveRoomsTable.vue
- resources/js/Jetstream/Modal.vue
- resources/js/app.js
- routes/api.php
- tests/Feature/ReservationControllerTest.php
- tests/Javascript/Components/AvailabilitiesModal.spec.js
Show availabilities/non-availabilities/blackout/bookings in a mini calendar
- See checks
- closes #247
> feat(#247): show availabilities in a calendar

- resources/js/Components/Tables/ViewActiveRoomsTable.vue
Fixes bug involving the route of the blackouts page
- closes #423
> fix(#423): Adjusts route for blackout room in ViewActiveRoomsTable

- composer.json
- composer.lock
- config/enlightn.php
- package-lock.json
- package.json
- tests/Artillery/load-tests.yml
- tests/Artillery/logins.csv
This PR adds a few useful performance testing tools to our repository.
- Enlightn - a PHP / Laravel focused performance / quality / security analyzer. Spots frequent causes of bottlenecks such as N+1 queries and various vulnerabilities like XSS attacks.
- Artillery - a node.js powered load testing tool that simulates various user defined scenarios at scale to test the concurrency capabilities of a web app system.
- closes #375
> #375 - Performance Testing Tools

- .circleci/config.yml
- tests/DuskTestCase.php
- closes #459
Blocked by https://github.com/CSU-Booking-Platform/container-spec/pull/10
> fix(#459): Fix CI

- app/Providers/AppServiceProvider.php
> fix(#467): Disable dusk in staging

- resources/js/Pages/Requestee/EditBookingForm.vue
The "Update Booking Request" form would not allow users to successfully update their bookings with new files, this MR fixes the issue.
- closes #443
> Fix update form file submission

- app/Http/Controllers/SettingsController.php
- app/Http/Middleware/HandleInertiaRequests.php
- resources/js/Components/Navbar/Navbar.vue
- resources/views/app.blade.php
- resources/views/app_head.blade.php
- resources/views/layouts/guest.blade.php
- tests/Browser/SettingsPageTest.php
- tests/Feature/SettingsControllerTest.php
Adding fix for app_logo file save and use app_title for page header instead of just the tab title. 
Makes app_logo more secure.
Adds more relevance to the app title feature. 
Update Settings test to check for the correct hash. 
Adding Frontend test to check if the title displays. 
- closes #448 
- closes #447 
- closes #229
> Settings updates

- resources/views/app_head.blade.php
> chore: Add hotjar to staging

- app/Http/Controllers/BookingRequestController.php
- resources/js/Components/Tables/BookingsTable.vue
- resources/js/Pages/Admin/BookingRequests/ViewBookingRequestStatusModal.vue
The button to view a booking request status was missing, this bug fix replaces it in the new UI table and creates a log when a file is uploaded to a request.
- closes #444
> Fix view booking status

- resources/js/Components/Tables/RoleTable.vue
- resources/js/Pages/Admin/Roles/CreateRoleForm.vue
- resources/js/Pages/Admin/Roles/Index.vue
- tests/Javascript/Components/Tables/RoleTable.spec.js
Update the roles UI to match the mockups
- closes #337
> 337 roles UI update

- .editorconfig
we should follow PSR-2 coding standards: http://www.php-fig.org/psr/psr-2/
> chore: revert php indents to 4

- resources/css/global.css
- resources/js/Components/Navbar/Navbar.vue
- resources/js/Components/Navbar/SubNavLink.vue
- tests/Feature/BlackoutControllerTest.php
Updated the Navbar to match the stakeholder's mockup suggestions.
Adjusts the navbar to more closely match the mockups after stakeholder review (Moves to the top-right of the app, changes the color to blend into the background)
- closes #483
> feat(#483): Update navbar UI

- resources/css/global.css
- resources/js/Components/Tables/BlackoutsTable.vue
- resources/js/Components/Tables/BookingsTable.vue
- resources/js/Components/Tables/RoleTable.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Components/Tables/UsersTable.vue
- resources/js/Components/Tables/ViewActiveRoomsTable.vue
- resources/js/Layouts/AppLayout.vue
- resources/js/Pages/Admin/Blackouts/Room.vue
- resources/js/Pages/Admin/BookingRequests/Index.vue
- resources/js/Pages/Admin/Roles/CreateRoleForm.vue
- resources/js/Pages/Admin/Roles/Index.vue
- resources/js/Pages/Admin/Rooms/Index.vue
- resources/js/Pages/Admin/Users/Index.vue
- resources/js/Pages/Requestee/BookingsList.vue
- tests/Browser/Pages/Rooms.php
- tests/Javascript/Components/Tables/RoomTable.spec.js
- tests/Javascript/Components/Tables/ViewActiveRoomsTable.spec.js
- tests/Javascript/Pages/Admin/BookingRequests/CreateBookingRequestModal.spec.js
- tests/Javascript/Pages/Admin/BookingRequests/UpdateBookingRequestForm.spec.js
- tests/Javascript/Pages/Admin/Roles/UpdateRoleForm.spec.js
- tests/Javascript/Pages/Admin/Rooms/UpdateRoomForm.spec.js
Tables more closely follow the stakeholder's requirements for UI.
- closes #484, #335
> feat(#484): Changed UI for tables accross all views

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/ReservationsController.php
- app/Models/Room.php
- tests/Feature/BookingRequestControllerTest.php
initial date selection now has working validation and the final booking request creation reuses it to make sure they are still valid. 
Tests now check for proper attribute title as well as bookings now use reservation functions so the old tests are able to be reused. 
- closes #445
> fix(#445): validation runs on both initial form and final form

- app/Http/Controllers/BookingRequestController.php
- database/seeders/RolesAndPermissionsSeeder.php
- resources/css/app.css
- resources/css/global.css
- resources/js/Components/Navbar/Navbar.vue
- resources/views/app_head.blade.php
- routes/api.php
- routes/web.php
- tests/Feature/BlackoutControllerTest.php
- tests/Feature/BookingRequestControllerTest.php
- tests/Feature/ReservationControllerTest.php
- tests/Feature/RoleControllerTest.php
- tests/Feature/RoomControllerTest.php
- tests/Feature/SettingsControllerTest.php
- tests/Feature/UserControllerTest.php
- tests/Javascript/Components/Navbar/Navbar.spec.js
- tests/TestCase.php
- tests/Unit/FilterRoomsTest.php
Updating all app routes with appropriate permissions
> fix(#478): Update permissions in application

- tests/Browser/RoomsPageTest.php
> fix(#503): Fix flaky test

- app/Console/Commands/MakeUser.php
- app/Console/Kernel.php
> fix(#510): Add command to create user

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/BookingReviewController.php
- app/Models/BookingRequest.php
- resources/js/Components/Tables/BookingsTable.vue
- resources/js/Pages/Admin/BookingRequests/ViewBookingRequestStatusModal.vue
- resources/js/Pages/Requestee/ViewBooking.vue
- routes/web.php
- tests/Feature/BookingRequestControllerTest.php
- tests/Feature/BookingReviewControllerTest.php
- tests/Javascript/Pages/Approval/ViewBooking.spec.js
need to wait for model constants to be made and then add tests
Users can not update their request while it is being reviewed
Reuse asset to review booking so testing is mostly just testing backend controllers and status changes 
- closes #249
> feat(#249): lock request while in review

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/SettingsController.php
- package-lock.json
- package.json
- resources/js/Components/RichTextEditor.vue
- resources/js/Pages/Admin/Settings/BookingInformations.vue
- resources/js/Pages/Admin/Settings/Index.vue
- resources/js/Pages/Requestee/BookingForm.vue
- resources/js/Pages/Requestee/EditBookingForm.vue
- routes/api.php
- tests/Feature/SettingsControllerTest.php
- tests/Javascript/Components/RichTextEditor.spec.js
- tests/Javascript/Pages/Admin/Settings/BookingInformations.spec.js
- tests/Javascript/Pages/Requestee/BookingForm.spec.js
- tests/Javascript/Pages/Requestee/EditBookingForm.spec.js
> feat(#477): rich-text-editor-and-apply

- resources/js/Components/Form/SortableUpload.vue
- resources/js/Components/Tables/BookingsTable.vue
- tests/Javascript/Components/Form/SortableUpload.spec.js
#425 
1. Add one or more files in the create booking form.
2. Remove all files.
3. Submit will crash on the backend because a string was sent instead of a binary object (file).
1. Add one or more files in the create booking form.
2. Remove all files.
3. Submit works correctly.
- closes #425
> fix: missing null check on reference object

- app/Notifications/BookingUpdateNotification.php
- app/Observers/BookingObserver.php
- app/Providers/EventServiceProvider.php
Adds email notification when a booking is approved or denied.
- closes #25
> feat(#25): Status Change Notification

- app/Http/Controllers/BookingRequestController.php
- app/Http/Controllers/BookingReviewController.php
- app/Models/BookingRequest.php
- resources/js/Components/Tables/AdminBookingRequestTable.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Pages/Approval/Index.vue
- routes/api.php
- tests/Javascript/Components/Tables/AdminBookingRequestTable.spec.js
- tests/Unit/FilterBookingRequestsTest.php
Created an admin table to view and have the ability to filter by assignee, status and date created. Also have a text input filter to further filter if necessary. If admins want or need to find booking requests with these parameters, this problem is solved.
- closes #463
> feat(#463): created admin booking req table

- app/Http/Controllers/DashboardController.php
- resources/js/Components/DashboardMetrics.vue
- resources/js/Pages/Dashboard.vue
- routes/web.php
- tests/Feature/DashboardControllerTest.php
- tests/Javascript/Pages/Dashboard.spec.js
Updated the Dashboard UI for admins, showing them app statistics depending on their roles.
This is the fixed form of PR #541 
Adds more information on an admin's dashboard, depending on what permissions they have (users who have "users" permissions can see user stats, rooms permissions show room stats etc.
Admin Dashboard
Regular User Dashboard
- closes #334
> feat(#334): Update Dashboard UI - Fix

- resources/js/Components/Tables/AdminBookingRequestTable.vue
UX issue - makes it clearer and easier for the user to distinguish the status of a booking.
No testing required, this is strictly a visual change
- closes #534
> task(#534): added color coding to statuses

- app/Models/Role.php
- phpunit.xml
- resources/js/Pages/Admin/Roles/CreateRoleForm.vue
- tests/ApplicationUsers.php
- tests/Browser/AdminRoles.php
- tests/DuskTestCase.php
- tests/TestCase.php
Quick PR to share some dusk testing improvements
> dusk updates

- resources/js/Components/RoomDetailedView.vue
- resources/js/Components/Tables/RoomTable.vue
- tests/Javascript/Components/Tables/RoomTable.spec.js
Added column sorting on click in this table, to make it easier for users to find the rooms they are looking to book. Also added a column to show capacity at first glance.
- closes #528
> 528 table sorting

- app/Http/Controllers/BookingRequestController.php
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- tests/Feature/BookingRequestControllerTest.php
- tests/Javascript/Pages/Admin/BookingRequests/CreateBookingRequestModal.spec.js
Minimum booking duration is required to be 30 minutes.
- closes #526
> 526 min booking time 30 mins

- resources/js/Components/Tables/RoomTable.vue
> feat(#533): Change room ID to room Name

- resources/js/Components/Availabilities.vue
- tests/Javascript/Components/Availabilities.spec.js
> feat(#524): Format date without seconds

- app/Models/User.php
- resources/js/Components/Navbar/Navbar.vue
Adds a badge next to the bookings -> review link with the counts of bookings the logged in user has to review.
- nothing significant code changes = no new code to cover
- closes #536
> task(#536): add bookings to review badge onto navbar

- resources/js/Components/Tables/RoomTable.vue
At request of stakeholders
User testing revealed that stakeholders were confused by the wording, and they asked that it be changed.
Changed one word.
- closes #531
> fix(#531): Changed word "advanced" to "filter"

- resources/js/Components/Navbar/Navbar.vue
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- resources/js/Pages/Requestee/BookingForm.vue
- tests/Javascript/Components/Navbar/Navbar.spec.js
- tests/Javascript/Pages/Requestee/BookingForm.spec.js
Nav bar will only show the "create" nav-item while a booking request form is currently in the works; otherwise the "create" nav-item will be hidden.
- closes #530
> #530 togle create nav item fresh

- resources/js/Pages/Admin/Settings/AcademicDate.vue
- resources/js/Pages/Admin/Settings/AppConfig.vue
- resources/js/Pages/Admin/Settings/AppLogo.vue
- resources/js/Pages/Admin/Settings/AppName.vue
- resources/js/Pages/Admin/Settings/BookingInformations.vue
- resources/js/Pages/Admin/Settings/CivicHoliday.vue
> feat(#565): provide a description for admin settings

- .circleci/config.yml
- .github/release.sh
> fix(#593): Run Browser tests in parallel & Upload assets to github with release

- resources/js/Components/RichTextEditor.vue
Add some styling to richtexteditor
Before: 
After:
- closes #564
> feat(#564): ui improvements on richTextEditor

- app/Http/Controllers/UserController.php
- resources/js/Pages/Admin/Users/ResetLinkModal.vue
- resources/js/Pages/Admin/Users/UsersList.vue
- routes/api.php
- tests/Feature/BookingReviewControllerTest.php
- tests/Feature/ReservationControllerTest.php
- tests/Feature/UserControllerTest.php
- tests/Javascript/Pages/Admin/Users/RestLinkModal.spec.js
- tests/Javascript/Pages/Admin/Users/UsersList.spec.js
> fix(#517): Admin can generate a resetLink for user

- resources/js/Components/Tables/RoleTable.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Components/Tables/UsersTable.vue
- resources/js/Components/Tables/ViewActiveRoomsTable.vue
- resources/js/Pages/Admin/Users/UsersList.vue
- tests/Browser/Pages/Roles.php
- tests/Browser/Pages/Rooms.php
- tests/Browser/Pages/Users.php
Replaced all buttons (except for "Open Details" in review page since it's a nav-link) with proper buttons following our app's style.
Also adjusted the action menu in Rooms to line up menu items
Replaces buttons with ones that are easier to see and click
- closes #574
> Fix(#574): Update action buttons

- resources/js/Components/Form/DateTimePicker.vue
- resources/js/Components/Tables/ViewActiveRoomsTable.vue
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- tests/Browser/Components/DateTimePicker.php
- tests/Browser/Pages/Rooms.php
- tests/Browser/RoomsPageTest.php
- tests/Browser/SearchPageTest.php
> add dusk test for #250

- resources/js/Layouts/AppLayout.vue
- resources/views/auth/login.blade.php
Updated social/contact links in footer, and removed Subscribe form
The subscribe form used on other csu sites requires access to their Mailchimp account which we do not have. 
- closes #597
> feat(#597): Update Footer

- resources/js/Components/Availabilities.vue
- resources/js/Pages/Admin/Blackouts/CreateBlackoutForm.vue
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
- resources/js/Pages/Admin/Settings/AcademicDate.vue
- resources/js/Pages/Admin/Settings/CivicHoliday.vue
- tests/Browser/BlackoutsPageTest.php
- tests/Browser/BookingsSearchTest.php
- tests/Browser/RoomsPageTest.php
- tests/Browser/SettingsPageTest.php
added some dusk test
- closes #XXXX
> Dusk test update

- tests/Browser/SearchPageTest.php
Added dusk test for issues #18 and #22
> fix(#22): Added dusk tests for #22 and #18

- tests/Browser/SearchPageTest.php
Add the dusk test
- applies tp #330
> fix(#330): add quick dusk test

- resources/js/Components/AvailabilitiesModal.vue
- resources/js/Components/Form/Select.vue
- resources/js/Components/RoomDetailedView.vue
- resources/js/Jetstream/Modal.vue
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- tests/Browser/BookingsSearchTest.php
- tests/Browser/Components/DateTimePicker.php
- tests/Browser/SearchPageTest.php
- tests/Javascript/Pages/Admin/BookingRequests/CreateBookingRequestModal.spec.js
> fix(#518): Improve new booking modal

- resources/js/Components/Tables/AdminBookingRequestTable.vue
- tests/Browser/ReviewIndexPageTest.php
Adds a dusk test to test both the api filter and the ext filter
- applies to #463
> fix(#463): add quick dusk test

- resources/js/Components/FormSection.vue
- resources/js/Layouts/AppLayout.vue
- resources/js/Pages/Admin/Rooms/CreateRoomForm.vue
- resources/js/Pages/Admin/Rooms/Index.vue
UI Improvements: 
- closes #602
> fix(#602): Improve UI for Create Room form

- resources/js/Components/DashboardMetrics.vue
- resources/js/Components/Navbar/Navbar.vue
- resources/js/Components/Tables/AdminBookingRequestTable.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Components/Tables/ViewActiveRoomsTable.vue
- resources/js/Pages/Admin/Blackouts/BlackoutList.vue
- resources/js/Pages/Admin/BookingRequests/BookingRequestsList.vue
- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- resources/js/Pages/Admin/Users/UsersList.vue
- resources/js/Pages/Requestee/EditBookingForm.vue
- resources/js/bootstrap.js
> Resolve sonar issues

- resources/js/Pages/Admin/BookingRequests/CreateBookingRequestModal.vue
- tests/Browser/BookRoomsTest.php
- tests/Browser/SearchPageTest.php
adds a dusk test to see if we can make a booking with multiple dates 
- applies to  #252
> fix(#252): dusk test for multi date booking

- app/Http/Controllers/Admin/BookingReviewController.php
- resources/js/Components/Navbar/Navbar.vue
- resources/js/Pages/Approval/Index.vue
- tests/Browser/BookingApprovalsTest.php
Covers #24 as described in AT criterias from #188
`php artisan dusk`
- closes #188
> test(#188): AT for #24 - Bookings Require Approval

- database/seeders/RolesAndPermissionsSeeder.php
- resources/js/Pages/Requestee/BookingForm.vue
- tests/Browser/BookingsPageTest.php
Covers #255 as described in AT criterias from #313 
`php artisan dusk`
- closes #313
> test(#313): AT for #255 - prompted for additional information when my booking request has certain attributes

- tests/Browser/BookRoomsTest.php
- tests/Browser/BookingsPageTest.php
- tests/Browser/BookingsSearchTest.php
- tests/Browser/ReviewIndexPageTest.php
- tests/Browser/RoomsPageTest.php
- tests/Browser/SearchPageTest.php
- tests/Browser/SettingsPageTest.php
- tests/Browser/UsersPageTest.php
Rename dusk tests to match acceptance test naming
- closes #623
> chore(#623): update test names to match acceptance tests

- app/Models/Room.php
- resources/js/Pages/Admin/Blackouts/BlackoutList.vue
- tests/Browser/SearchPageTest.php
also fix the wording of out of bounds date validations
- Fixes issue with editing blackouts.
- Also fixes wording for some room validation messages.
1. Seed the DB and login as an admin
1. Create a new blackout
1. Attempt to edit it
clicking nevermind fails to dimiss modal
clicking nevermind dismisses the modal
- closes #642
> fix(#642): fix issue with dismissing edit modal on BlackoutList.vue

- .env.example
- webpack.mix.js
Quick & minor configuration adjustment
- closes #630
> fix(#630): Configure mix to use version strings for cache busting

- app/Http/Controllers/Bookings/BookingRequestController.php
- app/Models/Room.php
- tests/Feature/ReservationControllerTest.php
> feat(#641): Add validation for blackouts

- resources/js/Components/Navbar/Navbar.vue
- resources/views/errors/503.blade.php
After removing the old "create" link page, "search" was renamed to avoid confusion.
Branded the maintenance page with CSU logos and colors
- closes #634 and #629
> #634 and #629, changed "search" to "new" and branded maintenance mode page

- resources/js/Components/BookingDetailedView.vue
- resources/js/Components/RichTextEditor.vue
- resources/js/Pages/Approval/ReviewBooking.vue
Fixes to the comments UX as well as the text box submit button.
- closes #605, 
- closes #663
- closes #673
> Send button and form UI fixes

- app/Http/Controllers/Admin/UserController.php
- resources/js/Components/Tables/CalendarViewTable.vue
- resources/js/Pages/Admin/Users/ResetLinkModal.vue
- tests/Javascript/Pages/Admin/Users/ResetLinkModal.spec.js
Small fixes 
- Closes #637 
- Closes #662
> Various fixes and improvements

- resources/js/Components/Tables/RoomTable.vue
- resources/js/Pages/Admin/BookingRequests/Index.vue
- tests/Javascript/Components/Tables/RoomTable.spec.js
- tests/Javascript/Pages/Admin/BookingRequests/Index.spec.js
Fixes filtering bug introduced by the pagination of rooms on search page
N/A
- closes #680
> bug(#680): fixed filter bug on search page

- app/Http/Controllers/Bookings/BookingRequestController.php
- app/Models/Room.php
- database/migrations/2021_04_10_195515_add_permission_restriction_override.php
- database/seeders/RolesAndPermissionsSeeder.php
- tests/Browser/SearchPageTest.php
- tests/Feature/RoomCustomDateRestrictionsTest.php
- tests/Feature/RoomRestrictionsTest.php
Remove TODO and the dead code attached to it. 
Also add new permission to by pass room day restrictions and number of bookings per semester
- closes #668 
- closes #656
> chore(#668) and feat(#656)

- app/Http/Controllers/Bookings/BookingRequestController.php
- resources/js/Components/BookingDetailedView.vue
- resources/js/Components/InitialReservationDetails.vue
- resources/js/Components/ReservationsList.vue
- resources/js/Pages/Requestee/BookingForm.vue
- resources/js/Pages/Requestee/EditBookingForm.vue
- tests/Javascript/Components/InitialReservationDetails.spec.js
- tests/Javascript/Pages/Requestee/BookingForm.spec.js
- tests/Javascript/Pages/Requestee/EditBookingForm.spec.js
- Updates BookingForm.vue / EditBookingForm.vue to support showing recurring reservations
- Reuse reservations table from BookingDetailsView by extracting into its own component
- reduce duplicate code by extracting InitialReservationDetails from the booking create / edit forms
Added new test for new component
- closes #667
> feat(#667): show a ReservationsList on forms if booking is recurring

- app/Models/Room.php
- tests/Browser/SearchPageTest.php
Validation message closes #654
> fix(#654): fixing validation message aka learning how to english

- resources/views/errors/503.blade.php
Now there's only one body tag containing the styling.
- closes #678
> fix(#678): Resolve sonar code smell

- tests/Feature/BookingRequestControllerTest.php
Looking into why this test is flacky on CI environment
- closes #652
> chore(#652): seeing if setting the time helps

- resources/js/Components/RoomDetailedView.vue
- resources/js/Components/Tables/AdminBookingRequestTable.vue
- resources/js/Components/Tables/BookingsTable.vue
- resources/js/Components/Tables/RoomTable.vue
- resources/js/Pages/Admin/BookingRequests/ViewBookingRequestStatusModal.vue
- resources/js/Pages/Admin/Rooms/Index.vue
- resources/js/Pages/Admin/Rooms/UpdateRoomForm.vue
Modal scroll issue, zindex, changed date input to datepicker
- closes #657 
- closes #666
- closes #664
> task(#657): fixed modal scroll issue

- resources/js/Components/Availabilities.vue
- tests/Javascript/Components/Availabilities.spec.js
Remove the old calendar since we got a new one
- closes #658
> feat(#658): remove calendar

- resources/js/Components/Form/DateTimePicker.vue
Added general color too the calendar (same as form buttons)
- closes #660
> feat(#660): change colors

- resources/js/Components/RoomDetailedView.vue
> fix(#658): remove unecessary room details if not present

- app/Http/Controllers/Bookings/BookingRequestController.php
- app/Http/Controllers/Bookings/ReservationsController.php
- app/Models/Room.php
- resources/js/Components/Form/DatePicker.vue
- resources/js/Pages/Admin/Settings/AcademicDate.vue
- resources/js/Pages/Requestee/BookingForm.vue
- tests/Browser/Components/DateTimePicker.php
- tests/Browser/SettingsPageTest.php
- tests/Feature/BookingRequestControllerTest.php
- tests/Feature/ReservationControllerTest.php
Added new Date Picker to the academic calendar in the settings page. Also, added verification to min days in advance to validate if alcohol or food is checked. 
- closes #655
- closes #670
> Updates for issues #655 and #670

- app/Actions/Fortify/UpdateUserProfileInformation.php
- resources/js/Pages/Profile/Show.vue
- resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- tests/Browser/Components/DateTimePicker.php
- tests/Browser/SearchPageTest.php
- tests/Feature/BookingRequestControllerTest.php
Profile fields of phone number and organization were not editable and needed to be made editable.
- closes #746
> task(#746): made phone and organization editable in profile
